name: Test Python implementation

on:
  push:
    paths:
      - '.github/workflows/python.yml'
      - 'python3/**'
  pull_request:
    paths:
      - '.github/workflows/python.yml'
      - 'python3/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install prerequisites
      run: |
        cd FrodoKEM
        pip3 install bitstring cryptography
    - name: Run basic test
      run: |
        cd FrodoKEM/python3
        python3 nist_kat.py
