name: Test Python implementation

on:
  push:
    paths:
      - '.github/workflows/python_ephemeral.yml'
      - 'python3/**'
  pull_request:
    paths:
      - '.github/workflows/python_ephemeral.yml'
      - 'python3/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install prerequisites
      run: |
        cd eFrodoKEM
        pip3 install bitstring cryptography
    - name: Run basic test
      run: |
        cd eFrodoKEM/python3
        python3 nist_kat.py
